### ISSUE TITLE
How generate this pass?

### ISSUE THREAD

**Issue by shadowfolder** [hashcat/maskprocessor#5]
I need generate /a/b/c/d/path.jpg where a,b,c,d needs tobe charset abcdefghijklmnopqrstuvwxyz0123456789

what code i need?

**Comment by AddaxSoft** [comment]
you would want to run:
`mp64 -1 abcdefghijklmnopqrstuvwxyz0123456789 ?1/?1/?1/?1/path.jpg -o urls.txt`

![image](https://cloud.githubusercontent.com/assets/6898938/23409442/ec2329d8-fdcb-11e6-838c-c670e7225203.png)

**Comment by Xanadrel** [comment]
Or even shorter define `-1 ?l?d`
