### ISSUE TITLE
auto increment from 1 char

### ISSUE THREAD

**Issue by sh1n0b1** [hashcat/maskprocessor#6]
Trying to generate a wordlist with max and min of 8 chars but maskprocessor keep starting from 1 char: 

```
bash-3.2$ ./mp64.bin "?a?a?a?a?a?a?a?a" | head

       !
       "
       #
       $
       %
       &
       '
       (
       )
```

Tried to manually specify the length using --increment, but it doesn't work either:
```
bash-3.2$ ./mp64.bin --increment=8:8 "?a?a?a?a?a?a?a?a" | head

       !
       "
       #
       $
       %
       &
       '
       (
       )
```
It looks like this is only an issue when using all character sets "?a".
I'm able to bypass this issue by doing:
```
./mp64.bin -1 "?l?u?d?s" "?1?1?1?1?1?1?1?1" | head
aaaaaaaa
aaaaaaab
aaaaaaac
aaaaaaad
aaaaaaae
```

**Comment by Xanadrel** [comment]
No issue, it's 8 chars, it just starts with the space.
